name: Update lean-3.*.* branch

on:
  schedule:
   - cron: '*/30 * * * *' # every 30 minutes

jobs:
  update_lean_3x_branch:
    runs-on: ubuntu-latest
    name: Update lean-3.*.* branch
    steps:

    - name: checkout mathlib
      uses: actions/checkout@v2
      with:
        repository: leanprover-community/mathlib
        token: ${{ secrets.LCB_TOKEN }}
        fetch-depth: 0

    - name: update branch
      run: |
        branch_name="lean-$(grep -oP '\d+\.\d+\.\d+' leanpkg.toml)"
        echo "Updating mathlib branch $branch_name to match master"
        git push origin HEAD:refs/heads/$branch_name
