name: post triage issues on Zulip

on:
  push:
  # schedule:
  #  - cron: '0 14 * * *'

jobs:
  post_issues:
    runs-on: ubuntu-latest
    name: Post random issue to zulip for triage
    steps:

    - name: Checkout scripts
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub zulip

    - name: Post issue on Zulip
      run: python post_issue_on_zulip.py "${{ secrets.RANDOM_ISSUE_BOT_ZULIP_TOKEN }}" "${{ secrets.LCB_TOKEN }}"
