name: Weekly blog and website report

on:
  schedule:
    - cron: '0 4 * * WED'  # Run at 04:00 UTC every Wednesday
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    if: github.repository == 'leanprover-community/azure-scripts'

    steps:
    - name: Checkout script
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: 'leanprover-community/azure-scripts'
        sparse-checkout: 'formatGhPrList.sh'
        path: script

    - name: Checkout website
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: 'leanprover-community/leanprover-community.github.io'
        path: website

    - name: Checkout blog
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: 'leanprover-community/leanprover-community.github.io'
        path: blog


    - name: Produce tables
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: tables
      run: |
        for site in website blog
        do
          printf 'PRs in %s\n' "${site}"
          cd "${site}"
          printf $'%s<<EOF\n%s\nEOF' "${site}" "$(./../script/formatGhPrList.sh "${site}")" | tee -a "$GITHUB_OUTPUT"
          cd ..
        done

    - name: Post output to Zulip
      uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5 # v1.0.2
      with:
        api-key: ${{ secrets.REPO_UPDATE_ZULIP_TOKEN }}
        email: 'leanprover-community-repo-update-bot@leanprover.zulipchat.com'
        organization-url: 'https://leanprover.zulipchat.com'
        to: 'mathlib reviewers'
        type: 'stream'
        topic: 'blog and website PRs'
        content: |
          ###  Open website PRs

          ${{ steps.tables.outputs.website }}

          ###  Open blog PRs

          ${{ steps.tables.outputs.table }}

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c # v1.2.1
